# Generated by Django 5.0.2 on 2025-05-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=200)),
                ('processing_capacity', models.TextField(help_text='Capacité de transformation')),
                ('products_processed', models.TextField(help_text='Types de produits transformés')),
                ('raw_material_needs', models.TextField(help_text='Besoins en matières premières')),
                ('equipment', models.TextField(help_text='Équipements disponibles')),
                ('certification_documents', models.FileField(blank=True, upload_to='certifications/processors/')),
                ('facility_photos', models.ImageField(blank=True, upload_to='facilities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Transformateur',
                'verbose_name_plural': 'Profils Transformateurs',
            },
        ),
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('farm_location', models.CharField(max_length=200)),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Taille en hectares', max_digits=10)),
                ('crops', models.TextField(help_text='Liste des cultures produites')),
                ('production_capacity', models.TextField(help_text='Capacité de production annuelle')),
                ('availability_period', models.CharField(help_text='Période de disponibilité des produits', max_length=100)),
                ('farming_method', models.CharField(help_text="Méthode d'agriculture (conventionnelle, biologique, etc.)", max_length=50)),
                ('certification_documents', models.FileField(blank=True, upload_to='certifications/producers/')),
                ('farm_photos', models.ImageField(blank=True, upload_to='farms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Producteur',
                'verbose_name_plural': 'Profils Producteurs',
            },
        ),
    ]
