# Generated by Django 5.0.2 on 2025-05-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility_photos/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='farm_photos/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='processorprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producerprofile',
            options={},
        ),
        migrations.RenameField(
            model_name='processorprofile',
            old_name='company_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='producerprofile',
            old_name='farm_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='processorprofile',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='processorprofile',
            name='processing_capacity',
        ),
        migrations.RemoveField(
            model_name='processorprofile',
            name='products_processed',
        ),
        migrations.RemoveField(
            model_name='processorprofile',
            name='raw_material_needs',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='availability_period',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='crops',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='farm_size',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='farming_method',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='production_capacity',
        ),
        migrations.AddField(
            model_name='processorprofile',
            name='company_description',
            field=models.TextField(default='Aucune description disponible'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='farm_description',
            field=models.TextField(default='Aucune description disponible'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='processorprofile',
            name='certification_documents',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='processorprofile',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='processorprofile',
            name='facility_photos',
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='certification_documents',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='farm_name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='farm_photos',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('ml', 'Millilitre'), ('unite', 'Unité')], max_length=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='profiles.producerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('planting', 'Plantation'), ('harvesting', 'Récolte'), ('maintenance', 'Maintenance'), ('other', 'Autre')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='profiles.producerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='processorprofile',
            name='facility_photos',
            field=models.ManyToManyField(blank=True, to='profiles.facilityphoto'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='farm_photos',
            field=models.ManyToManyField(blank=True, to='profiles.farmphoto'),
        ),
    ]
