# Generated by Django 5.0.2 on 2025-05-06 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_facilityphoto_farmphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processorprofile',
            name='plantation_photos',
            field=models.ImageField(blank=True, help_text='Photos de vos plantations', null=True, upload_to='plantation_photos/'),
        ),
        migrations.AlterField(
            model_name='processorprofile',
            name='company_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processorprofile',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='processorprofile',
            name='facility_photos',
        ),
        migrations.AlterField(
            model_name='processorprofile',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='processorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processorprofile',
            name='facility_photos',
            field=models.ImageField(blank=True, null=True, upload_to='facility_photos/'),
        ),
    ]
