# Generated by Django 5.0.2 on 2025-05-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processorprofile',
            name='facility_photos',
        ),
        migrations.RemoveField(
            model_name='processorprofile',
            name='plantation_photos',
        ),
        migrations.AddField(
            model_name='facilityphoto',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.processorprofile'),
        ),
        migrations.AlterField(
            model_name='facilityphoto',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PlantationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plantation_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.processorprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
