# Generated by Django 5.0.2 on 2025-05-07 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_processorprofile_facility_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='processor_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('photo_type', models.CharField(choices=[('facility', 'Installation'), ('machine', 'Machine')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.processorprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProducerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='producer_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('photo_type', models.CharField(choices=[('plantation', 'Plantation'), ('crop', 'Culture')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.producerprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
