# Generated by Django 5.0.2 on 2025-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_processorphoto_producerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorprofile',
            name='transformation_capacity',
            field=models.TextField(blank=True, help_text='Capacité de transformation (tonnes par jour/mois, etc.)'),
        ),
        migrations.AddField(
            model_name='processorprofile',
            name='transformed_products',
            field=models.TextField(blank=True, help_text='Liste des produits transformés'),
        ),
    ]
