# Generated by Django 5.0.2 on 2025-05-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_processorprofile_transformation_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processorprofile',
            name='certification_documents',
            field=models.FileField(blank=True, null=True, upload_to='certification_documents/'),
        ),
        migrations.AlterField(
            model_name='processorprofile',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='processorprofile',
            name='transformation_capacity',
            field=models.CharField(help_text='Capacité de transformation (ex: 1000 tonnes/an)', max_length=200),
        ),
        migrations.AlterField(
            model_name='processorprofile',
            name='transformed_products',
            field=models.TextField(help_text='Liste des produits transformés'),
        ),
    ]
