# Generated by Django 5.0.2 on 2025-05-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_processorprofile_certification_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='crops',
            field=models.TextField(default='', help_text='Liste des cultures produites'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='production_capacity',
            field=models.CharField(default='', help_text='Capacité de production (ex: 100 tonnes/an)', max_length=200),
        ),
    ]
