# Generated by Django 5.0.2 on 2025-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_certified',
            new_name='business_registration_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_registration',
            field=models.FileField(blank=True, help_text="Extrait Kbis ou document d'enregistrement de l'entreprise", null=True, upload_to='business_registrations/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_document',
            field=models.FileField(blank=True, help_text="Document d'identité (CNI, passeport, etc.)", null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='land_title',
            field=models.FileField(blank=True, help_text='Titre foncier ou document prouvant la propriété/exploitation des terres', null=True, upload_to='land_titles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='land_title_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tax_registration',
            field=models.FileField(blank=True, help_text="Numéro d'identification fiscale", null=True, upload_to='tax_registrations/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tax_registration_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('producer', 'Producteur'), ('processor', 'Transformateur')], max_length=20),
        ),
    ]
