# Generated by Django 5.0.2 on 2025-05-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
