# Generated by Django 5.0.2 on 2025-05-07 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('terminated', 'Terminé')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True, help_text='Conditions du partenariat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_partnerships', to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_partnerships', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership', to='messaging.partnershiprequest')),
            ],
            options={
                'verbose_name': 'Partenariat',
                'verbose_name_plural': 'Partenariats',
                'ordering': ['-created_at'],
                'unique_together': {('producer', 'processor')},
            },
        ),
    ]
